### ISSUE TITLE
Null Attributes should not be excluded from the Release Object

### ISSUE THREAD

**Issue by rexovas** [joalla/discogs_client#129]
I've come across a few instances where, say - the "country" attribute is missing from a release

Take this one for example: 
https://www.discogs.com/release/18424870-The-Smashing-Pumpkins-Rotten-Apples-Greatest-Hits

In the case of the missing year, I'm still able to access the year attribute without a KeyError
```
>>> release.data["year"]
0
```

However when attempting to access the country attribute:
```
release.data["country"]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
KeyError: 'country'
```

This makes it rather clunky to handle cases where certain attributes are missing - because in some cases after catching a KeyError, I simply need to call `release.refresh()` and the keys may then become accessible

But if the key is truly missing, a value (such as 0 in the case of the year) can convey that.

I'm not sure if this is an api client issue or an issue from Discogs side

**Comment by AnssiAhola** [comment]
Hey @rexovas
Thanks for reporting this.

I tried printing out the raw response from the discogs API and it indeed seems like the `year` is 0 and the `country` is missing
```python
print(client._get("https://api.discogs.com/releases/18424870"))
```

> This makes it rather clunky to handle cases where certain attributes are missing - because in some cases after catching a KeyError, I simply need to call release.refresh() and the keys may then become accessible (side note, would be nice if I didn't have to call release.refresh())

You can use the `fetch` method to get the attributes instead of using the `data` attribute directly.
This refreshes the object once if the given attribute wasn't found initially and tries again.
```python
release.fetch("year")
release.fetch("country")
```
Also does it not work if you access the `release` properties normally?
```python
release.year
release.country
```
This uses the `fetch` method in the background so it should refresh automatically.

**Comment by rexovas** [comment]
Thanks - will give these a try and report back

**Comment by rexovas** [comment]
Pardon the delay - reporting back.

You're suggestion of `release.fetch()` worked perfectly for my use case.  It prevented the need for me to `try` `except KeyError`  and call `release.refresh()`.

One thing to note, I did notice slight differences between using fetch or accessing the release properties normally.  For example `release.fetch("labels")` yields something like 
```
>>> release = client.release(17)
>>> labels = release.fetch('labels')
>>> labels
[{'name': 'Intrinsic Design', 'catno': 'ID001-6', 'entity_type': '1', 'entity_type_name': 'Label', 'id': 26, 'resource_url': 'https://api.discogs.com/labels/26', 'thumbnail_url': 'https://i.discogs.com/Pvo5Ml9Ub4ITB7mFVKW--AZ5L169FOIcFX1du89FeXo/rs:fit/g:sm/q:40/h:228/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTI2LTE2/NDI2NTg3OTUtNDc1/Ni5qcGVn.jpeg'}]

>>> labels[0]["name"]
'Intrinsic Design'
```

Whereas release.labels results in:
```
>>> release = client.release(17)
>>> release.labels
[<Label 26 'Intrinsic Design'>]

>>> release.labels[0]["name"]
TypeError: 'Label' object is not subscriptable
```

Just wanted to note that the results are not always the same.

**Comment by JOJ0** [comment]
@AnssiAhola are we considering to add things that are actually missing in the API already to the client? If we start to do that, there is no end. Isn't this kind of out of scope? Just thinking out loud if this should be a reasonable feature request or a "works as designed".

**Comment by AnssiAhola** [comment]
> @AnssiAhola are we considering to add things that are actually missing in the API already to the client? If we start to do that, there is no end. Isn't this kind of out of scope? Just thinking out loud if this should be a reasonable feature request or a "works as designed".
> 
> Or am I mistaken and we return a default value of "None" already when requesting something that is not existing in the API already?
> 
> ```
> release.country
> ```
> 
> I couldn't figure it out from the discussion above...

The client uses `None` as the default value for data that is missing from the response, yes.

I'm fine with "works as designed" for now, we can come back to this if it ever comes up.
